export const SINGUP_USER = "SINGUP_USER";
export const LOGIN_USER = "LOGIN_USER";
export const VERIFY_SESSION = "VERIFY_SESSION";
export const CURRENT_USER = "CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";
// Errors
export const SINGUP_USER_ERROR = "SINGUP_USER_ERROR";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const NOT_CURRENT_USER = "NOT_CURRENT_USER";
