// AUTH
export const SINGUP_USER = "SINGUP_USER";
export const LOGIN_USER = "LOGIN_USER";
export const VERIFY_SESSION = "VERIFY_SESSION";
export const CURRENT_USER = "CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";

// USER
export const USER_DATA = "USER_DATA";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const DELETE_USER = "DELETE_USER";
// WALLET
export const CREATE_WALLET = "CREATE_WALLET";
export const DELETE_WALLET = "DELETE_WALLET";

// Errors
export const SINGUP_USER_ERROR = "SINGUP_USER_ERROR";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const NOT_CURRENT_USER = "NOT_CURRENT_USER";
export const ERROR_CREATE_WALLET = "ERROR_CREATE_WALLET";
export const ERROR_DELETE_WALLET = "ERROR_DELETE_WALLET";
